./tests/template_tests/tests.py:458: warning: test_templates has 84 NLOC,2
./tests/test_client_regress/tests.py:30: warning: test_contains has 81 NLOC,1
./django/templatetags/i18n.py:370: warning: do_block_translate has 62 NLOC,1
./django/middleware/common.py:39: warning: process_request has 47 NLOC,1
./django/forms/models.py:625: warning: validate_unique has 42 NLOC,3
./django/forms/forms.py:146: warning: _html_output has 51 NLOC,1
./django/core/management/commands/inspectdb.py:32: warning: handle_inspection has 83 NLOC,2
./django/core/management/commands/makemessages.py:47: warning: process has 94 NLOC,2
./django/core/management/commands/dumpdata.py:33: warning: handle has 80 NLOC,2
./django/core/management/commands/loaddata.py:166: warning: _find_fixtures has 38 NLOC,1
./django/core/management/commands/syncdb.py:27: warning: handle_noargs has 95 NLOC,1
./django/core/management/__init__.py:275: warning: autocomplete has 36 NLOC,1
./django/core/management/templates.py:65: warning: handle has 99 NLOC,1
./django/core/management/validation.py:22: warning: get_validation_errors has 270 NLOC,1
./django/core/serializers/python.py:77: warning: Deserializer has 39 NLOC,1
./django/core/handlers/base.py:74: warning: get_response has 99 NLOC,1
./django/core/servers/fastcgi.py:90: warning: runfastcgi has 78 NLOC,1
./django/core/urlresolvers.py:262: warning: _populate has 47 NLOC,2
./django/test/_doctest.py:905: warning: _find has 44 NLOC,2
./django/template/base.py:902: warning: token_kwargs has 29 NLOC,1
./django/template/defaulttags.py:142: warning: render has 56 NLOC,2
./django/utils/unittest/loader.py:97: warning: loadTestsFromName has 37 NLOC,1
./django/utils/unittest/case.py:300: warning: run has 69 NLOC,1
./django/utils/unittest/main.py:114: warning: parseArgs has 35 NLOC,1
./django/utils/translation/trans_real.py:489: warning: templatize has 154 NLOC,1
./django/utils/html.py:215: warning: urlize has 51 NLOC,1
./django/utils/regex_helper.py:46: warning: normalize has 88 NLOC,2
./django/utils/six.py:697: warning: print_ has 40 NLOC,1
./django/utils/dictconfig.py:274: warning: configure has 108 NLOC,2
./django/utils/ipv6.py:144: warning: is_valid_ipv6_address has 32 NLOC,1
./django/utils/module_loading.py:35: warning: module_has_submodule has 49 NLOC,1
./django/contrib/formtools/wizard/views.py:124: warning: get_initkwargs has 30 NLOC,1
./django/contrib/comments/views/comments.py:32: warning: post_comment has 72 NLOC,1
./django/contrib/auth/management/commands/createsuperuser.py:49: warning: handle has 78 NLOC,1
./django/contrib/admin/templatetags/admin_list.py:176: warning: items_for_result has 63 NLOC,2
./django/contrib/admin/static/admin/js/jquery.min.js:3: warning: init has 1 NLOC,11
./django/contrib/admin/static/admin/js/SelectFilter2.js:140: warning: filter_key_down has 16 NLOC,1
./django/contrib/admin/static/admin/js/jquery.js:123: warning: init has 60 NLOC,34
./django/contrib/admin/options.py:281: warning: lookup_allowed has 31 NLOC,4
./django/contrib/admin/util.py:268: warning: label_for_field has 44 NLOC,1
./django/contrib/contenttypes/management.py:9: warning: update_contenttypes has 63 NLOC,1
./django/contrib/contenttypes/views.py:9: warning: shortcut has 49 NLOC,1
./django/contrib/gis/utils/layermapping.py:146: warning: check_layer has 54 NLOC,2
./django/contrib/gis/static/gis/js/OLMapWidget.js:163: warning: MapWidget has 86 NLOC,1
./django/contrib/gis/db/backends/postgis/operations.py:464: warning: spatial_lookup_sql has 46 NLOC,1
./django/contrib/gis/db/models/sql/compiler.py:15: warning: get_columns has 67 NLOC,1
./django/contrib/gis/db/models/query.py:576: warning: _distance_attribute has 85 NLOC,1
./django/contrib/gis/templates/gis/google/google-map.js:0: warning: *global* has 35 NLOC,8
./django/contrib/admindocs/views.py:180: warning: model_detail has 80 NLOC,1
./django/http/multipartparser.py:98: warning: parse has 102 NLOC,1
./django/db/backends/oracle/creation.py:50: warning: _create_test_db has 62 NLOC,1
./django/db/backends/oracle/base.py:223: warning: convert_values has 23 NLOC,1
./django/db/backends/creation.py:40: warning: sql_create_model has 69 NLOC,1
./django/db/models/fields/related.py:330: warning: __set__ has 28 NLOC,1
./django/db/models/sql/compiler.py:65: warning: as_sql has 61 NLOC,5
./django/db/models/sql/query.py:411: warning: combine has 67 NLOC,4
./django/db/models/sql/where.py:166: warning: make_atom has 74 NLOC,1
./django/db/models/query.py:160: warning: iterator has 72 NLOC,3
./django/db/models/deletion.py:240: warning: delete has 35 NLOC,1
./django/db/models/base.py:58: warning: __new__ has 127 NLOC,3
./django/db/transaction.py:283: warning: __exit__ has 57 NLOC,1
./django/views/decorators/http.py:78: warning: condition.condition.decorator.inner has 62 NLOC,1
./django/views/debug.py:250: warning: get_traceback_data has 61 NLOC,1
./django/views/i18n.py:187: warning: get_javascript_catalog has 68 NLOC,1